<?php

/*
 * Load assets
 */
function assets()
{
  // Load theme css
  wp_enqueue_style('impactsix_css', get_template_directory_uri().'/dist/css/screen.css', array(), null, false);
}

add_action('wp_enqueue_scripts', 'assets');

/**
 * This function will register the nav menu.
 *
 * @method register_my_menus
 */
function register_my_menus()
{
    register_nav_menus(
    array(
      'header-menu' => __('Header')
    )
  );
}
add_action('init', 'register_my_menus');

add_action( 'admin_init', 'my_remove_admin_menus' );
function my_remove_admin_menus() {
    remove_menu_page( 'edit-comments.php' );
}



//add_action( 'admin_menu', 'impact_six_change_post_menu_label' );
//add_action( 'init', 'impact_six_change_post_object_label' );
function impact_six_change_post_menu_label() {
	global $menu;
	global $submenu;
	$menu[5][0] = 'Works';
	$submenu['edit.php'][5][0] = 'Works';
	$submenu['edit.php'][10][0] = 'Add Works';
	$submenu['edit.php'][16][0] = 'Works Tags';
	echo '';
}
function impact_six_change_post_object_label() {
	global $wp_post_types;
	$labels = &$wp_post_types['post']->labels;
	$labels->name = 'Works';
	$labels->singular_name = 'Works';
	$labels->add_new = 'Add Work';
	$labels->add_new_item = 'Add Work';
	$labels->edit_item = 'Edit Work';
	$labels->new_item = 'Works';
	$labels->view_item = 'View Works';
	$labels->search_items = 'Search Works';
	$labels->not_found = 'No News found';
	$labels->not_found_in_trash = 'No News found in Trash';
}

/*
 * Custom Post type
 */

function post_type_work()
{
    $labels = array(
        'name' => 'Works',
        'singular_name' => 'Work',
        'menu_name' => 'Work',
        'name_admin_bar' => 'work',
        'add_new' => 'Add New',
        'add_new_item' => 'Add work',
        'new_item' => 'New work',
        'edit_item' => 'Edit work',
        'view_item' => 'View work',
        'all_items' => 'All works',
        'search_items' => 'Search works',
        'parent_item_colon' => 'Parent works:',
        'not_found' => 'No projects found.',
        'not_found_in_trash' => 'No projects found in Trash.',
    );

    $args = array(
        'labels' => $labels,
        'public' => true,
        'rewrite' => array('slug' => 'work'),
        'has_archive' => false,
        'menu_position' => 5,
        'menu_icon' => 'dashicons-portfolio',
        'taxonomies' => array('post_tag', 'category'),
        'supports' => array('title'),
    );
    register_post_type('works', $args);
}
add_action('init', 'post_type_work');


function post_type_client()
{
    $labels = array(
        'name' => 'Team',
        'singular_name' => 'Member',
        'menu_name' => 'Team',
        'name_admin_bar' => 'Team',
        'add_new' => 'Add New',
        'add_new_item' => 'Add member to team',
        'new_item' => 'New member',
        'edit_item' => 'Edit member',
        'view_item' => 'View member',
        'all_items' => 'All members',
        'search_items' => 'Search members',
        'parent_item_colon' => 'Parent members:',
        'not_found' => 'No projects found.',
        'not_found_in_trash' => 'No projects found in Trash.',
    );

    $args = array(
        'labels' => $labels,
        'public' => true,
        'rewrite' => array('slug' => 'members'),
        'has_archive' => false,
        'menu_position' => 5,
        'menu_icon' => 'dashicons-admin-users',
        //'menu_icon' => get_stylesheet_directory_uri() . '/functions/panel/images/catchinternet-small.png',
        'taxonomies'          => array( '' ),
        'supports' => array('title', 'editor', 'author', 'thumbnail', 'excerpt', 'custom-fields', 'comments'),
    );
    register_post_type('teams', $args);
}
add_action('init', 'post_type_client');


function post_type_ad()
{
    $labels = array(
        'name' => 'Ads',
        'singular_name' => 'Ad',
        'menu_name' => 'Ad',
        'name_admin_bar' => 'Ad',
        'add_new' => 'Add New',
        'add_new_item' => 'Add an ad block',
        'new_item' => 'New ad',
        'edit_item' => 'Edit ad',
        'view_item' => 'View ad',
        'all_items' => 'All ads',
        'search_items' => 'Search ads',
        'parent_item_colon' => 'Parent ads:',
        'not_found' => 'No projects found.',
        'not_found_in_trash' => 'No projects found in Trash.',
    );

    $args = array(
        'labels' => $labels,
        'public' => true,
        'rewrite' => array('slug' => 'ads'),
        'has_archive' => false,
        'menu_position' => 4,
        'menu_icon' => 'dashicons-admin-users',
        'taxonomies'          => array( '' ),
        'supports' => array('title', 'editor', 'author', 'thumbnail', 'excerpt', 'custom-fields', 'comments'),
    );
    register_post_type('ads', $args);
}
add_action('init', 'post_type_ad');

/*
 * Allow svg files
 */
function cc_mime_types($mimes) {
  $mimes['svg'] = 'image/svg+xml';
  return $mimes;
}
add_filter('upload_mimes', 'cc_mime_types');
/*
 * ACF Pro Functions
 */
if (function_exists('acf_add_options_page')) {
    acf_add_options_page(array(
        'page_title' => 'Global Settings',
        'menu_title' => 'Global',
        'menu_slug' => 'global-settings',
        'capability' => 'edit_posts',
        'redirect' => false,
    ));
}

add_theme_support( 'post-thumbnails' );


if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_59d17a11cfb73',
    'title' => 'About Page',
    'fields' => array(
      array(
        'key' => 'field_59d17a16037df',
        'label' => 'Featured Image',
        'name' => 'featured_image',
        'type' => 'image',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59d17a27037e0',
        'label' => 'Featured Thumbnail',
        'name' => 'featured_thumbnail',
        'type' => 'image',
        'instructions' => 'Recommended Size 111x113 pixels',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59d17a44037e1',
        'label' => 'Featured Heading',
        'name' => 'featured_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59d17a53037e2',
        'label' => 'Featured Body',
        'name' => 'featured_body',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'wpautop',
      ),
      array(
        'key' => 'field_5bfe9be29cc9f',
        'label' => 'Show Clients',
        'name' => 'show_clients',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_59d17efea9412',
        'label' => 'Clients',
        'name' => 'clients',
        'type' => 'gallery',
        'instructions' => 'Recommended Image Size 120x120px',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'min' => '',
        'max' => '',
        'insert' => 'append',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59d18676e8b6d',
        'label' => 'Client CTA',
        'name' => 'client_cta',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59d186b5e8b6e',
        'label' => 'Client CTA Position',
        'name' => 'client_cta_position',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5bfe9bf39cca0',
        'label' => 'Show Featured Section',
        'name' => 'show_featured_section',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_59d17f71a9416',
        'label' => 'Featured Image 2',
        'name' => 'featured_image_2',
        'type' => 'image',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59d17f38a9413',
        'label' => 'Featured Body 2',
        'name' => 'featured_body_2',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'wpautop',
      ),
      array(
        'key' => 'field_59d17f56a9414',
        'label' => 'Featured CTA Label',
        'name' => 'featured_cta_label',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59d17f66a9415',
        'label' => 'Featured CTA Email',
        'name' => 'featured_cta_url',
        'type' => 'email',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page',
          'operator' => '==',
          'value' => '19',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'discussion',
      3 => 'comments',
      4 => 'author',
      5 => 'format',
      6 => 'page_attributes',
      7 => 'featured_image',
      8 => 'categories',
      9 => 'tags',
      10 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_59db9fe34aa3f',
    'title' => 'Ad Block',
    'fields' => array(
      array(
        'key' => 'field_59d439cc1fe28',
        'label' => 'Image',
        'name' => 'image',
        'type' => 'image',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59d439e21fe29',
        'label' => 'URL',
        'name' => 'url',
        'type' => 'url',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_59d43a0f1fe2b',
        'label' => 'Display',
        'name' => 'display',
        'type' => 'radio',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'all' => 'All',
          'mobile' => 'Mobile',
          'desktop' => 'Desktop',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'all',
        'layout' => 'horizontal',
        'return_format' => 'value',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'ads',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'custom_fields',
      3 => 'discussion',
      4 => 'comments',
      5 => 'slug',
      6 => 'author',
      7 => 'format',
      8 => 'page_attributes',
      9 => 'featured_image',
      10 => 'categories',
      11 => 'tags',
      12 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_59c07c2e146dc',
    'title' => 'Clients',
    'fields' => array(
      array(
        'key' => 'field_59c07c3100a84',
        'label' => 'Logo',
        'name' => 'logo',
        'type' => 'image',
        'instructions' => 'Recommended file size 120px x 120px',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'post',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_59c3363d6645b',
    'title' => 'Connect',
    'fields' => array(
      array(
        'key' => 'field_59c33646c1f9f',
        'label' => 'Heading',
        'name' => 'heading',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'br',
      ),
      array(
        'key' => 'field_59c33662c1fa0',
        'label' => 'Sub Heading',
        'name' => 'sub_heading',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'br',
      ),
      array(
        'key' => 'field_59c33684c1fa1',
        'label' => 'Address',
        'name' => 'address',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'row',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_59c33707c1fa3',
            'label' => 'Address',
            'name' => 'address',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => '',
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_59c33bd9bf1cd',
            'label' => 'Google Maps Location Title',
            'name' => 'google_maps_location_title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_59c336f5c1fa2',
            'label' => 'Google Maps URL',
            'name' => 'google_maps_url',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_59c33772c1fa5',
            'label' => 'Google Maps Latitude',
            'name' => 'google_maps_latitude',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_59c3373ac1fa4',
            'label' => 'Google Maps Longitude',
            'name' => 'google_maps_longitude',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_59c33f17ffda5',
        'label' => 'Phone Number',
        'name' => 'phone_number',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59c33f35ffda6',
        'label' => 'Email',
        'name' => 'email',
        'type' => 'email',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'template-connect.php',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'custom_fields',
      3 => 'discussion',
      4 => 'comments',
      5 => 'featured_image',
      6 => 'categories',
      7 => 'tags',
      8 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_59c331df09596',
    'title' => 'Global',
    'fields' => array(
      array(
        'key' => 'field_5b564f277b835',
        'label' => 'Fav Icon',
        'name' => 'fav_icon',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59c331e4e60e4',
        'label' => 'Logo',
        'name' => 'logo',
        'type' => 'file',
        'instructions' => 'Upload a .svg file of your logo',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => 'svg',
      ),
      array(
        'key' => 'field_59d11c66c95d8',
        'label' => 'Facebook URL',
        'name' => 'facebook_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_59d1234eae12c',
        'label' => 'Facebook Icon',
        'name' => 'facebook_icon',
        'type' => 'file',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59d11ca7c95d9',
        'label' => 'Twitter URL',
        'name' => 'twitter_url',
        'type' => 'url',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_59d12363ae12d',
        'label' => 'Twitter Icon',
        'name' => 'twitter_icon',
        'type' => 'file',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'library' => 'all',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5a207629a34d4',
        'label' => 'Social Media',
        'name' => 'social_media',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_5a20763aa34d5',
            'label' => 'Title',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5a207640a34d6',
            'label' => 'URL',
            'name' => 'url',
            'type' => 'url',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5a207648a34d7',
            'label' => 'Icon',
            'name' => 'icon',
            'type' => 'file',
            'instructions' => '.SVG icons only',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'svg',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'global-settings',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_59cb11c1b4163',
    'title' => 'Home Page',
    'fields' => array(
      array(
        'key' => 'field_59cb11c76af33',
        'label' => 'Featured Work',
        'name' => 'featured_work',
        'type' => 'post_object',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'works',
          1 => 'ads',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 1,
        'return_format' => 'object',
        'ui' => 1,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page',
          'operator' => '==',
          'value' => '2',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'discussion',
      3 => 'comments',
      4 => 'author',
      5 => 'format',
      6 => 'featured_image',
      7 => 'categories',
      8 => 'tags',
      9 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_59c07adec155a',
    'title' => 'Team',
    'fields' => array(
      array(
        'key' => 'field_59d1783609b65',
        'label' => 'Thumbnail',
        'name' => 'thumbnail',
        'type' => 'image',
        'instructions' => 'Recommended Size 111x113 pixels',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59c07ae3caad3',
        'label' => 'Job Title',
        'name' => 'job_title',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59c07afdcaad4',
        'label' => 'Headline',
        'name' => 'headline',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59c07b4dcaad5',
        'label' => 'Body',
        'name' => 'body',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'wpautop',
      ),
      array(
        'key' => 'field_59c07b6acaad6',
        'label' => 'Call to Action Label',
        'name' => 'call_to_action_label',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59c07b99caad7',
        'label' => 'Call to Action Email',
        'name' => 'call_to_action_email',
        'type' => 'email',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'teams',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'custom_fields',
      3 => 'discussion',
      4 => 'comments',
      5 => 'author',
      6 => 'format',
      7 => 'page_attributes',
      8 => 'categories',
      9 => 'tags',
      10 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_59d191887864c',
    'title' => 'Work Page',
    'fields' => array(
      array(
        'key' => 'field_59d1918df76a0',
        'label' => 'Featured Work',
        'name' => 'featured',
        'type' => 'post_object',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'works',
        ),
        'taxonomy' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'return_format' => 'object',
        'ui' => 1,
      ),
      array(
        'key' => 'field_59d1932ff0ea8',
        'label' => 'Up Next Text',
        'name' => 'up_next_text',
        'type' => 'text',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59d1992816cab',
        'label' => 'Category',
        'name' => 'category',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => '',
        'sub_fields' => array(
          array(
            'key' => 'field_59d1993d16cac',
            'label' => 'Highlighted Word',
            'name' => 'highlighted_word',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_59d199cc16cad',
            'label' => 'Non Highlighted Word',
            'name' => 'non_highlighted_word',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_59d1987d97e14',
            'label' => 'Category Relationship',
            'name' => 'category_relationship',
            'type' => 'taxonomy',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'taxonomy' => 'category',
            'field_type' => 'select',
            'allow_null' => 0,
            'add_term' => 1,
            'save_terms' => 0,
            'load_terms' => 0,
            'return_format' => 'id',
            'multiple' => 0,
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'page',
          'operator' => '==',
          'value' => '21',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_59cae2f0723f3',
    'title' => 'Works',
    'fields' => array(
      array(
        'key' => 'field_59d1924613cae',
        'label' => 'Featured Image',
        'name' => 'featured_image',
        'type' => 'image',
        'instructions' => 'This will be the image that will be displayed on the "Work" Page if featured.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59d1928213cb0',
        'label' => 'Excerpt',
        'name' => 'excerpt',
        'type' => 'wysiwyg',
        'instructions' => 'This will be used on the work page as the intro text.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 1,
        'delay' => 0,
      ),
      array(
        'key' => 'field_59cae606d84dd',
        'label' => 'Thumbnail Image',
        'name' => 'thumbnail_image',
        'type' => 'image',
        'instructions' => 'Recommended Size 500px x 375px',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'full',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_59cae3b1f115c',
        'label' => 'Thumbnail Heading',
        'name' => 'thumbnail_heading',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59cae3d0f115d',
        'label' => 'Thumbnail Subheading',
        'name' => 'thumbnail_subheading',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_59cae2f5f115b',
        'label' => 'Intro',
        'name' => 'intro',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
      array(
        'key' => 'field_59caef49c3711',
        'label' => 'Body Enhanced',
        'name' => 'body_enhanced',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layouts' => array(
          '59d065ca793f9' => array(
            'key' => '59d065ca793f9',
            'name' => 'text',
            'label' => 'Text',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_59d065e93c4e7',
                'label' => 'Text',
                'name' => 'text_block',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 0,
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '59d066de2a542' => array(
            'key' => '59d066de2a542',
            'name' => 'image',
            'label' => 'Image',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_59d066de2a544',
                'label' => 'Image',
                'name' => 'image_block',
                'type' => 'image',
                'instructions' => 'images should be cut at 400,500,600,700,800,900, 1000 widths. I recommend you not exceed 700px in height so people can view your images in their entirety without scrolling (no partial views on desktop of images because they are too tall)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
              array(
                'key' => 'field_59d155c280402',
                'label' => 'Max Width',
                'name' => 'max_width',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  400 => '400px',
                  500 => '500px',
                  600 => '600px',
                  700 => '700px',
                  800 => '800px',
                  900 => '900px',
                  1000 => '1000px',
                ),
                'default_value' => array(
                  0 => 1000,
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
          '59d16bf39ce9a' => array(
            'key' => '59d16bf39ce9a',
            'name' => 'video',
            'label' => 'Video',
            'display' => 'block',
            'sub_fields' => array(
              array(
                'key' => 'field_59d16bf39ce9b',
                'label' => 'Video',
                'name' => 'video_block',
                'type' => 'file',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
              ),
              array(
                'key' => 'field_59d16c909ce9c',
                'label' => 'Auto Start',
                'name' => 'auto_start',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
              ),
            ),
            'min' => '',
            'max' => '',
          ),
        ),
        'button_label' => 'Add Row',
        'min' => '',
        'max' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'works',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'custom_fields',
      3 => 'discussion',
      4 => 'comments',
      5 => 'author',
      6 => 'format',
      7 => 'page_attributes',
      8 => 'featured_image',
      9 => 'tags',
      10 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

  endif;
